RedisURL: "redis://127.0.0.1:6379"
RedisChannelPrefix: "thumbnary:"
DBDriverName: "mysql"
DBDataSourceName: "root:root@tcp(127.0.0.1:3306)/thumbnary"
DBOriginTableName: "origin"

Server:
  Port: 9000
